---
- name: Check CUPS service status
  hosts: localhost  # Change this to your target hosts as needed
  become: yes  # This allows the playbook to run commands with sudo privileges
  tasks:
    - name: Check CUPS service status
      command: service cups status
      register: cups_status
      ignore_errors: yes  # Allows the playbook to continue even if the command fails

    - name: Display CUPS service status
      debug:
        msg: "CUPS service status: {{ cups_status.stdout }}"

    - name: Display CUPS service error (if any)
      debug:
        msg: "Error: {{ cups_status.stderr }}"
      when: cups_status.rc != 0  # Only display this if there was an error
