---
- name: Pull repository, copy and download files
  hosts: localhost
  tasks:
    - name: version file
      stat:
        path: "home/shreshta/version"
      register: version_client

    - name: version file
      stat:
        path: "home/shreshta/version"
      register: version_server
      
    - name: other files
      get_url:
        url: "https://raw.githubusercontent.com/Pradeep3122003/production/master/version"
      register: version_server
      
    - name: check version
      debug:
        msg: "Version up to date"
      when: version_server.stat.checksum == version_client.stat.checksum

    - name: Debug existing file status
      debug:
        msg: "File exists? {{ file_check.stat.exists }}"

    - name: Download file from repository (force overwrite)
      get_url:
        url: "https://raw.githubusercontent.com/Pradeep3122003/production/master/message.txt"
        dest: "/home/shreshta/message.txt"
        force: yes

    - name: Run cups_status.yml directly from GitHub
      command: ansible-pull -U https://github.com/Pradeep3122003/production.git cups_off.yml
      args:
        chdir: /home/shreshta  # Set the working directory if necessary
