---
- name: Manage CUPS Service and Notify Slack
  hosts: localhost
  gather_facts: no
  vars:
    slack_webhook_url: "https://hooks.slack.com/services/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"  # Replace with your actual Slack webhook URL

  tasks:
    - name: Check if CUPS service is running
      systemd:
        name: cups
        state: started
      register: cups_status

    - name: Turn off CUPS if it is running
      systemd:
        name: cups
        state: stopped
      when: cups_status.changed
      register: stop_cups

    - name: Prepare Slack message
      set_fact:
        slack_message: >
          {
            "text": "CUPS service was {{ 'stopped' if stop_cups.changed else 'not running' }}."
          }

    - name: Send notification to Slack
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ slack_message | to_json }}"
        body_format: json
      when: stop_cups.changed or cups_status.changed  # Send notification if service was stopped or not running
      ignore_errors: yes  # Continue if Slack notification fails
