---
- name: Pull repository, copy and download files
  hosts: localhost
  tasks:
    - name: Download file from repository
      get_url:
        url: "https://raw.githubusercontent.com/Pradeep3122003/production/master/message.txt"
        dest: "message.txt"
