---
- name: Pull repository, copy and download files
  hosts: localhost
  tasks:
    - name: Copy file from repository to /tmp
      copy:
        src: "production/message.txt"
        dest: "/message.txt"
    
    - name: Run additional Ansible tasks 
      command: service cups status
