---
- name: Pull repository, copy and download files
  hosts: localhost
  tasks:
    - name: Check if /tmp/message.txt exists
      stat:
        path: "/home/shreshta/message.txt"
      register: file_check

    - name: Debug existing file status
      debug:
        msg: "File exists? {{ file_check.stat.exists }}"

    - name: Download file from repository (force overwrite)
      get_url:
        url: "https://raw.githubusercontent.com/Pradeep3122003/production/master/message.txt"
        dest: "/home/shreshta/message.txt"
        force: yes

    - name: cups file run
      command: ansible-playbook https://raw.githubusercontent.com/Pradeep3122003/production/master/cups_status.yml
