---
- name: Pull repository, copy and download files
  hosts: localhost
  tasks:
    - name: Check client version
      stat:
        path: "/home/shreshta/version"
      register: version_client

    - name: Download server version from repository
      get_url:
        url: "https://raw.githubusercontent.com/Pradeep3122003/production/master/version"
        dest: "/home/shreshta/version_server"
        force: yes

    - name: Check server version file checksum
      stat:
        path: "/home/shreshta/version_server"
      register: version_server

    - name: Compare versions
      debug:
        msg: "Version up to date"
      when: version_server.stat.checksum == version_client.stat.checksum

    - name: Notify if versions are different
      debug:
        msg: "Versions are different"
      when: version_server.stat.checksum != version_client.stat.checksum

    - name: Overwrite client version with server version if they are different
      copy:
        src: "/home/shreshta/version_server"
        dest: "/home/shreshta/version"
        force: yes
      when: version_server.stat.checksum != version_client.stat.checksum

    - name: Download message.txt from repository (force overwrite)
      get_url:
        url: "https://raw.githubusercontent.com/Pradeep3122003/production/master/message.txt"
        dest: "/home/shreshta/message.txt"
        force: yes

    - name: Run cups_status.yml directly from GitHub
      command: ansible-pull -U https://github.com/Pradeep3122003/production.git cups_off.yml
      args:
        chdir: /home/shreshta  # Set the working directory if necessary
